# Fichier de configuration local pour l'envoi d'e-mails (NON COMMIT)
# Veuillez ne pas commiter ce fichier sur Git pour protéger vos identifiants.
Mail.smtp.host=smtp.gmail.commail.smtp.port=587mail.sender.email=khalil.elmnari@gmail.commail.sender.password=ohqrgcygvzbporzakhalil.elmnari@gmail.com
mail.sender.password=ohqrgcygvzbporza
