# Fichier de configuration local pour l'envoi d'e-mails (NON COMMIT)
# Veuillez ne pas commiter ce fichier sur Git pour protéger vos identifiants.

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.sender.email=khalil.elmnari@gmail.com
mail.sender.password=ohqrgcygvzbporza
